import { prisma } from "@/lib/db";
import { hashPassword } from "@/lib/auth";
import { APPROVAL, ROLES, TOURNAMENT_FORMATS } from "@/lib/constants";
import { generatePosterDataUri } from "@/lib/posterGenerator";
import { randomUUID } from "crypto";

const BOT_EMAIL = "bot@vantix.internal";

const GAMES = ["BGMI", "Free Fire", "Valorant", "COD Mobile", "Clash Royale", "Chess.com Blitz"];

const ADJECTIVES = ["Midnight", "Solo", "Rapid", "Clutch", "Ranked", "Iron", "Neon", "Rogue", "Prime", "Turbo"];
const NOUNS = ["Clash", "Showdown", "Skirmish", "Cup", "Rumble", "Circuit", "Gauntlet", "Faceoff", "Sprint", "League"];

const FORMATS = Object.values(TOURNAMENT_FORMATS);
const ENTRY_FEES = [0, 0, 10, 20, 30, 50];
const MAX_SLOTS = [16, 25, 32, 50, 64, null];

function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

async function getOrCreateBotOrganizer() {
  const existing = await prisma.user.findUnique({ where: { email: BOT_EMAIL } });
  if (existing) return existing;

  const passwordHash = await hashPassword(randomUUID());
  return prisma.user.create({
    data: {
      name: "Vantix Bot",
      email: BOT_EMAIL,
      passwordHash,
      role: ROLES.ORGANIZER,
      firmName: "Vantix Auto-Hosted",
      isVerified: true,
      bio: "Automated tournament host. These matches are system-generated to keep the lobby active.",
    },
  });
}

const PRIZE_PAYOUT_SHARE = 0.8; // 80% of the pooled entry fees goes to prizes; 20% covers hosting/admin
const ASSUMED_SLOTS_WHEN_UNLIMITED = 100;

function calculatePrizePool(entryFee: number, maxSlots: number | null): string | null {
  if (entryFee <= 0) return null;
  const capacity = maxSlots ?? ASSUMED_SLOTS_WHEN_UNLIMITED;
  const pool = Math.round((entryFee * capacity * PRIZE_PAYOUT_SHARE) / 10) * 10;
  return `₹${pool}`;
}

function randomDetails() {
  const game = pick(GAMES);
  const title = `${pick(ADJECTIVES)} ${game} ${pick(NOUNS)}`;
  const entryFee = pick(ENTRY_FEES);
  const maxSlots = pick(MAX_SLOTS);
  const prizePool = calculatePrizePool(entryFee, maxSlots);
  const hoursOut = 2 + Math.floor(Math.random() * 70);
  const startDate = new Date(Date.now() + hoursOut * 60 * 60 * 1000);
  const format = pick(FORMATS);

  const entryLine =
    entryFee > 0
      ? `Entry fee is ₹${entryFee} per squad (pay via the registration page; wallet payment supported). The prize pool is calculated as 80% of total collected entry fees${maxSlots ? ` at full capacity (${maxSlots} squads)` : ""}, paid out to the top finishers.`
      : "This is a free-entry match with no entry fee required.";

  const rules = [
    `Format: ${game} squad registration. Provide a valid contact number and all 4 squad members' in-game name/UID at registration — incomplete squads will be rejected.`,
    entryLine,
    "Room ID and password will be shared on your dashboard shortly before the match starts. Be online and ready at least 15 minutes early.",
    "Fair play is mandatory: no emulators on mobile-only matches, no teaming with rival squads, no smurfing, no hacks/cheats/exploits. Violators are permanently banned from the platform.",
    "Submit a clear screenshot of your final match result (placement/kills) immediately after the match ends. Entries without a valid result screenshot will not be considered for prize payout.",
    prizePool
      ? "Verified prize winnings are credited to your Vantix wallet within 48 hours of match completion and can be withdrawn from your wallet dashboard."
      : "This match does not carry a cash prize; it's hosted to keep the lobby active for practice and rank progress.",
    "All admin and organizer decisions on disputes, results, and eligibility are final.",
  ].join("\n");

  return {
    title,
    game,
    description: `An auto-hosted ${game} match generated by the Vantix bot to keep the lobby active. Registration details and squad rules follow the platform's standard format.`,
    rules,
    prizePool,
    entryFee,
    maxSlots,
    startDate,
    format,
    tags: "auto-hosted,community",
  };
}

export async function maybeRunBot() {
  const settings = await prisma.siteSettings.upsert({
    where: { id: "global" },
    update: {},
    create: { id: "global" },
  });

  if (!settings.botEnabled) return;

  const intervalMs = Math.max(1, settings.botIntervalMinutes) * 60 * 1000;
  const due = !settings.botLastRunAt || Date.now() - settings.botLastRunAt.getTime() >= intervalMs;
  if (!due) return;

  // Race-safe: only proceed if we can claim the run by advancing botLastRunAt
  // from the exact value we just read (loses the race harmlessly otherwise).
  const claimed = await prisma.siteSettings.updateMany({
    where: { id: "global", botLastRunAt: settings.botLastRunAt },
    data: { botLastRunAt: new Date() },
  });
  if (claimed.count === 0) return;

  const organizer = await getOrCreateBotOrganizer();
  const details = randomDetails();
  const bannerUrl = generatePosterDataUri({
    title: details.title,
    game: details.game,
    entryFee: details.entryFee,
    prizePool: details.prizePool,
  });

  await prisma.tournament.create({
    data: {
      ...details,
      bannerUrl,
      organizerId: organizer.id,
      status: APPROVAL.APPROVED,
      hostingFee: 0,
      hostingFeeVerified: true,
    },
  });
}
