import { prisma } from "@/lib/db";
import { hashPassword } from "@/lib/auth";
import { APPROVAL, ROLES, TOURNAMENT_FORMATS } from "@/lib/constants";
import { generatePosterDataUri } from "@/lib/posterGenerator";
import { randomUUID } from "crypto";

const BOT_EMAIL = "bot@vantix.internal";

const GAMES = ["BGMI", "Free Fire", "Valorant", "COD Mobile", "Clash Royale", "Chess.com Blitz"];

const ADJECTIVES = ["Midnight", "Solo", "Rapid", "Clutch", "Ranked", "Iron", "Neon", "Rogue", "Prime", "Turbo"];
const NOUNS = ["Clash", "Showdown", "Skirmish", "Cup", "Rumble", "Circuit", "Gauntlet", "Faceoff", "Sprint", "League"];

const FORMATS = Object.values(TOURNAMENT_FORMATS);
const ENTRY_FEES = [0, 0, 10, 20, 30, 50];
const MAX_SLOTS = [16, 25, 32, 50, 64, null];

function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

async function getOrCreateBotOrganizer() {
  const existing = await prisma.user.findUnique({ where: { email: BOT_EMAIL } });
  if (existing) return existing;

  const passwordHash = await hashPassword(randomUUID());
  return prisma.user.create({
    data: {
      name: "Vantix Bot",
      email: BOT_EMAIL,
      passwordHash,
      role: ROLES.ORGANIZER,
      firmName: "Vantix Auto-Hosted",
      isVerified: true,
      bio: "Automated tournament host. These matches are system-generated to keep the lobby active.",
    },
  });
}

function randomDetails() {
  const game = pick(GAMES);
  const title = `${pick(ADJECTIVES)} ${game} ${pick(NOUNS)}`;
  const entryFee = pick(ENTRY_FEES);
  const maxSlots = pick(MAX_SLOTS);
  const prizePool = entryFee > 0 ? `₹${Math.floor(entryFee * (maxSlots ?? 20) * 0.7)}` : null;
  const hoursOut = 2 + Math.floor(Math.random() * 70);
  const startDate = new Date(Date.now() + hoursOut * 60 * 60 * 1000);
  const format = pick(FORMATS);

  return {
    title,
    game,
    description: `An auto-hosted ${game} match generated by the Vantix bot to keep the lobby active. Registration details and squad rules follow the platform's standard format.`,
    rules: "Standard fair-play rules apply. No emulators, no teaming, no smurfing. Admin decisions are final.",
    prizePool,
    entryFee,
    maxSlots,
    startDate,
    format,
    tags: "auto-hosted,community",
  };
}

export async function maybeRunBot() {
  const settings = await prisma.siteSettings.upsert({
    where: { id: "global" },
    update: {},
    create: { id: "global" },
  });

  if (!settings.botEnabled) return;

  const intervalMs = Math.max(1, settings.botIntervalMinutes) * 60 * 1000;
  const due = !settings.botLastRunAt || Date.now() - settings.botLastRunAt.getTime() >= intervalMs;
  if (!due) return;

  // Race-safe: only proceed if we can claim the run by advancing botLastRunAt
  // from the exact value we just read (loses the race harmlessly otherwise).
  const claimed = await prisma.siteSettings.updateMany({
    where: { id: "global", botLastRunAt: settings.botLastRunAt },
    data: { botLastRunAt: new Date() },
  });
  if (claimed.count === 0) return;

  const organizer = await getOrCreateBotOrganizer();
  const details = randomDetails();
  const bannerUrl = generatePosterDataUri({
    title: details.title,
    game: details.game,
    entryFee: details.entryFee,
    prizePool: details.prizePool,
  });

  await prisma.tournament.create({
    data: {
      ...details,
      bannerUrl,
      organizerId: organizer.id,
      status: APPROVAL.APPROVED,
      hostingFee: 0,
      hostingFeeVerified: true,
    },
  });
}
